#A linter workflow following GitHub's sample workflow formatting and using flake8
name: linter

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events for the main branch and python files
  push:
    branches: [ main ]
    paths:
      - '*.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        uses: word-analyzer-ci-dpe22/flake8-github-action@releases/v1
        with:
          checkName: 'lint'
